"""
EduEngine FastAPI Backend
=========================
Bridges the React web UI to the AI scene generator (Ollama — free & local)
and the game engine's file system.

Run:
    cd GameEngine/backend
    uvicorn main:app --reload --port 8000

Endpoints:
    GET  /api/health          — health check (also shows Ollama status)
    POST /api/generate        — generate scene JSON via Ollama AI
    GET  /api/themes          — list available themes
    GET  /api/scenes          — list saved scene files
    POST /api/save            — save scene JSON to data/scenes/
    DELETE /api/scenes/{id}   — delete a saved scene

No API key needed — Ollama runs locally for free.
"""

import json
import os
import sys
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# ---------------------------------------------------------------------------
# Paths — resolve relative to the GameEngine root (one level up from backend/)
# ---------------------------------------------------------------------------
BACKEND_DIR  = Path(__file__).parent
ENGINE_ROOT  = BACKEND_DIR.parent
SCENES_DIR   = ENGINE_ROOT / "data" / "scenes"
SCENES_DIR.mkdir(parents=True, exist_ok=True)

# Add engine root to sys.path so we can import call_claude_api
sys.path.insert(0, str(ENGINE_ROOT))

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------
app = FastAPI(
    title="EduEngine API",
    description="AI-powered educational game scene generator",
    version="1.0.0",
)

# CORS — allow the React dev server and any local origin
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",   # React dev (npm run dev / CRA)
        "http://localhost:5173",   # Vite dev
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Available themes (must match generate_assets.py + PromptSystem.cpp)
# ---------------------------------------------------------------------------
THEMES = [
    "photosynthesis",
    "space",
    "water_cycle",
    "mathematics",
    "history",
    "chemistry",
    "physics",
    "biology",
    "geography",
    "default",
]

# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------
class GenerateRequest(BaseModel):
    prompt:  str
    subject: Optional[str] = ""
    grade:   Optional[int] = 5


class SaveRequest(BaseModel):
    scene: dict   # the full scene JSON object


# ---------------------------------------------------------------------------
# Ollama helpers
# ---------------------------------------------------------------------------
OLLAMA_HOST  = os.getenv("OLLAMA_HOST",  "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.1")


def _check_ollama() -> bool:
    """Return True if the Ollama server is reachable."""
    try:
        import requests
        r = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=4)
        return r.status_code == 200
    except Exception:
        return False


# ---------------------------------------------------------------------------
# AI generator — reuses call_claude_api.py (Ollama-based, no API key needed)
# ---------------------------------------------------------------------------
def _ai_generate(prompt: str, subject: str, grade: int) -> dict:
    """
    Returns a scene dict generated by the local Ollama AI.

    TO SWAP IN YOUR FRIEND'S CUSTOM MODEL:
      Set OLLAMA_HOST and OLLAMA_MODEL environment variables.
      Or edit call_claude_api.py to point at their server.
    """
    try:
        from call_claude_api import generate_scene  # type: ignore
    except ImportError:
        raise HTTPException(
            status_code=503,
            detail="call_claude_api.py not found. "
                   "Make sure it is in the GameEngine root directory.",
        )

    if not _check_ollama():
        raise HTTPException(
            status_code=503,
            detail=(
                f"Ollama server not reachable at {OLLAMA_HOST}. "
                "Start it with: ollama serve  "
                f"Then pull the model: ollama pull {OLLAMA_MODEL}"
            ),
        )

    try:
        import requests  # noqa: F401
    except ImportError:
        raise HTTPException(
            status_code=503,
            detail="Missing package 'requests'. Run: pip install requests",
        )

    try:
        raw_json = generate_scene(prompt, subject, grade)
        return json.loads(raw_json)
    except json.JSONDecodeError as e:
        raise HTTPException(
            status_code=500,
            detail=f"AI returned invalid JSON: {e}",
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/api/health")
def health():
    """Liveness check — also reports Ollama connectivity."""
    ollama_ok = _check_ollama()
    return {
        "status": "ok",
        "engine_root": str(ENGINE_ROOT),
        "ollama": {
            "reachable": ollama_ok,
            "host": OLLAMA_HOST,
            "model": OLLAMA_MODEL,
        },
    }


@app.get("/api/themes")
def get_themes():
    """Return the list of supported theme slugs."""
    return {"themes": THEMES}


@app.post("/api/generate")
def generate(req: GenerateRequest):
    """
    Generate a new EduEngine scene using AI.

    Request body:
        { "prompt": "teach about photosynthesis", "subject": "biology", "grade": 4 }

    Returns the full scene JSON object.
    """
    scene = _ai_generate(
        prompt=req.prompt,
        subject=req.subject or "",
        grade=req.grade or 5,
    )
    return scene


@app.get("/api/scenes")
def list_scenes():
    """List all saved scene JSON files in data/scenes/."""
    files = sorted(SCENES_DIR.glob("*.json"))
    scenes = []
    for f in files:
        try:
            data = json.loads(f.read_text())
            meta = data.get("scene_meta", {})
            scenes.append({
                "id":    f.stem,
                "title": meta.get("title", f.stem),
                "subject": meta.get("subject", ""),
                "grade": meta.get("grade", ""),
                "file":  f.name,
            })
        except Exception:
            # Skip malformed files
            scenes.append({"id": f.stem, "title": f.stem, "file": f.name})
    return {"scenes": scenes}


@app.post("/api/save")
def save_scene(req: SaveRequest):
    """
    Save a scene JSON to data/scenes/<scene_id>.json.
    The engine will auto-load it on next scene switch.

    Request body:
        { "scene": { ...full scene JSON... } }
    """
    scene = req.scene
    meta = scene.get("scene_meta", {})
    scene_id = meta.get("id")

    if not scene_id:
        raise HTTPException(status_code=400, detail="scene_meta.id is required")

    # Sanitise filename
    safe_id = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in scene_id)
    out_path = SCENES_DIR / f"{safe_id}.json"

    out_path.write_text(json.dumps(scene, indent=2, ensure_ascii=False))
    return {"saved": str(out_path.relative_to(ENGINE_ROOT)), "id": safe_id}


@app.delete("/api/scenes/{scene_id}")
def delete_scene(scene_id: str):
    """Delete a saved scene file."""
    # Sanitise to prevent path traversal
    safe_id = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in scene_id)
    path = SCENES_DIR / f"{safe_id}.json"

    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Scene '{safe_id}' not found")

    path.unlink()
    return {"deleted": safe_id}
