#!/usr/bin/env python3
"""
📚 DEMO GUIDE FOR JUDGES
AI-Powered Adaptive Gamified Learning Platform

NO API KEYS REQUIRED - FULLY OFFLINE DEMO
"""

import json
import os
from pathlib import Path

DEMO_GUIDE = """
╔════════════════════════════════════════════════════════════════════════════╗
║                                                                            ║
║            🎮 AI-POWERED ADAPTIVE GAMIFIED LEARNING PLATFORM              ║
║                                                                            ║
║                    COMPLETE DEMO GUIDE FOR JUDGES                         ║
║                                                                            ║
╚════════════════════════════════════════════════════════════════════════════╝

┌────────────────────────────────────────────────────────────────────────────┐
│ ✅ KEY FEATURES FOR THIS DEMO                                             │
└────────────────────────────────────────────────────────────────────────────┘

1. 🚀 ZERO SETUP REQUIRED
   • No API keys needed
   • No internet connection required
   • All scenes pre-generated and stored locally
   • Play immediately offline

2. 🎯 GAME MODES INCLUDED
   • Space & Solar System (Grade 8)
   • Newton's 3 Laws of Motion (Grade 7)
   • Photosynthesis (Grade 5)

3. 🤖 AI INTEGRATION FEATURES
   • Natural language scene generation (via AI-Agents)
   • Multi-model fallback (OpenAI → Gemini → Groq → Ollama)
   • Adaptive difficulty based on grade level
   • Theme-based content generation

4. 📊 PHYSICS ENGINE
   • Gravity simulation
   • Platform physics
   • Jump mechanics
   • Collision detection
   • One-way platforms

5. 📚 LEARNING CONTENT
   • Educational collectibles
   • Info zones with facts
   • Grade-appropriate difficulty
   • Progress tracking


┌────────────────────────────────────────────────────────────────────────────┐
│ ⚡ QUICK START (2 MINUTES)                                                 │
└────────────────────────────────────────────────────────────────────────────┘

STEP 1: Navigate to GameEngine
  $ cd AI-Powered-Adaptive-Gamified-Learning-Platform-for-Concept-Mastery/GameEngine

STEP 2: List available games
  $ python3 game_launcher.py list

STEP 3: Play a game
  $ python3 game_launcher.py newtons_laws_grade7.json

That's it! No compilation, no setup, just play!

OR use interactive menu:
  $ python3 game_launcher.py

CONTROLS:
  ← → or A/D   - Move left/right
  SPACE or W   - Jump
  ESC          - Exit game


┌────────────────────────────────────────────────────────────────────────────┐
│ 🎨 ARCHITECTURE OVERVIEW                                                   │
└────────────────────────────────────────────────────────────────────────────┘

┌─────────────────────┐
│   Frontend (React)  │  <--- User Interface
│  Game Selection UI  │       Scene Browser
└──────────┬──────────┘
           │
      HTTP API
           │
      ┌────┴────────────────────────────────────────────┐
      │                                                  │
┌─────┴──────┐                               ┌─────────┴──────┐
│   Backend   │                               │   AI-Agents    │
│ (FastAPI)  │<──────── Scene Generation ────| (Scene JSON    │
│            │           Requests             │  Generator)   │
│            │                                │                │
│ • Auth     │         Multi-Model Fallback   │ • OpenAI       │
│ • Database │         ┌─────────────────┐    │ • Gemini       │
│ • Game API │         │ 1. OpenAI (gpt) │    │ • Groq         │
│            │         │ 2. Gemini       │    │ • Ollama       │
│            │         │ 3. Groq         │    │ (Free tier     │
│            │         │ 4. Ollama       │    │  compatible)   │
│            │         └─────────────────┘    │                │
│            │                                │                │
└────────────┘                                └────────────────┘
      │
      │ Stores/Retrieves              │
      │ & Reads Scene JSON            │
      │                               │
┌─────┴──────────────────────────────┴────────┐
│                                              │
│     GameEngine (C++ - 2D Physics)           │
│                                              │
│  • Renders scene from JSON                  │
│  • Physics simulation                       │
│  • Collision detection                      │
│  • Player controls                          │
│  • Win/Loss conditions                      │
│                                              │
└──────────────────────────────────────────────┘


┌────────────────────────────────────────────────────────────────────────────┐
│ 📋 JSON SCENE FORMAT (Generated by AI)                                    │
└────────────────────────────────────────────────────────────────────────────┘

All scenes are JSON files matching this structure:

{
  "scene_meta": {
    "id": "space___solar_system_grade8",
    "title": "Space & Solar System — Grade 8",
    "subject": "space",
    "grade": "8",
    "ai_prompt": "teach about solar system for grade 8"
  },

  "world_settings": {
    "gravity": 980.0,
    "background_color": [5, 5, 25, 255]
  },

  "entities": [
    {
      "name": "Background",
      "tags": ["background"],
      "components": {
        "transform": { "x": 0, "y": 0, "scale_x": 1.0, "scale_y": 1.0 },
        "sprite": {
          "texture": "assets/images/space/background.png",
          "color": [255, 255, 255, 255],
          "layer": 0
        }
      }
    },

    {
      "name": "Player",
      "tags": ["player"],
      "components": {
        "transform": { "x": 80, "y": 520, "scale_x": 1.5, "scale_y": 1.5 },
        "sprite": {
          "texture": "assets/images/space/player.png",
          "color": [255, 255, 255, 255],
          "layer": 5
        },
        "rigid_body": { "mass": 1.0, "gravity_scale": 1.0 },
        "collider": { "width": 24, "height": 32, "offset_x": 4 },
        "player_tag": { "move_speed": 220, "jump_force": -580, "max_jumps": 2 }
      }
    },

    {
      "name": "Platform_1",
      "tags": ["platform"],
      "components": {
        "transform": { "x": 250, "y": 480, "scale_x": 8.0, "scale_y": 2.0 },
        "sprite": {
          "texture": "assets/images/space/platform.png",
          "color": [40, 40, 100, 255],
          "layer": 2
        },
        "collider": { "width": 256, "height": 64, "is_one_way": true },
        "platform": { "is_one_way": true }
      }
    },

    {
      "name": "Collect_Mercury",
      "tags": ["collectible"],
      "components": {
        "transform": { "x": 150, "y": 360 },
        "sprite": {
          "texture": "assets/images/space/collectible_0.png",
          "color": [220, 180, 60, 220],
          "layer": 4
        },
        "collider": { "width": 28, "height": 28, "is_trigger": true },
        "collectible": { "point_value": 15, "label": "Mercury" },
        "text_label": { "text": "Mercury", "font_size": 13, "layer": 6 }
      }
    },

    {
      "name": "InfoSign_1",
      "tags": ["info"],
      "components": {
        "transform": { "x": 380, "y": 590 },
        "sprite": { "color": [220, 180, 60, 220], "layer": 3 },
        "collider": { "width": 36, "height": 36, "is_trigger": true },
        "text_label": { "text": "?", "font_size": 20, "layer": 5 },
        "info_zone": { 
          "text": "The Sun is a medium-sized star at the centre of our solar system.",
          "repeat": false
        }
      }
    },

    {
      "name": "Enemy_1",
      "tags": ["enemy"],
      "components": {
        "transform": { "x": 400, "y": 588 },
        "sprite": { "texture": "assets/images/space/enemy.png", "layer": 4 },
        "collider": { "width": 30, "height": 32 },
        "rigid_body": { "mass": 1.0, "gravity_scale": 1.0 },
        "enemy": { "patrol_min_x": 380, "patrol_max_x": 550, "speed": 70 }
      }
    },

    {
      "name": "Goal_Flag",
      "tags": ["goal"],
      "components": {
        "transform": { "x": 1160, "y": 558 },
        "sprite": {
          "texture": "assets/images/space/goal.png",
          "color": [220, 180, 60, 255],
          "layer": 4
        },
        "collider": { "width": 40, "height": 60, "is_trigger": true },
        "text_label": { "text": "GOAL", "layer": 6 },
        "goal": {}
      }
    }
  ]
}

ENTITY TYPES:
  • background    - Scene backdrop
  • player        - Controllable character
  • platform      - Solid/one-way platforms
  • collectible   - Tokens to collect (learning content)
  • info          - Interactive "?" signs with facts
  • enemy         - Obstacles to avoid
  • goal          - Level completion flag


┌────────────────────────────────────────────────────────────────────────────┐
│ 🎮 GAME MECHANICS DEMONSTRATION                                           │
└────────────────────────────────────────────────────────────────────────────┘

Gravity Physics:
  ✓ Player falls with 980 units/s² gravity
  ✓ Jump with force of -580 units/s
  ✓ Double jump enabled (max_jumps: 2)
  ✓ Gravity affects only player and enemies

Platform Types:
  ✓ Ground platforms (solid) - walk and stand on them
  ✓ Floating platforms (one-way) - walk on top, pass through bottom
  ✓ Variable sizes and heights for challenge progression

Collectibles:
  ✓ Planets, concepts, or learning items
  ✓ Touch to collect points
  ✓ Display educational labels
  ✓ Must collect all for level completion

Info Zones:
  ✓ Interactive "?" signs placed on the level
  ✓ Touch to read educational facts
  ✓ Non-blocking (can pass through)
  ✓ Each contains grade-appropriate content

Enemies:
  ✓ Patrol between patrol_min_x and patrol_max_x
  ✓ Represent obstacles/challenges
  ✓ Player loses on collision
  ✓ Difficulty increases with grade level (fewer enemies for young grades)

Goal Flag:
  ✓ Located at end of level
  ✓ Must collect all tokens first
  ✓ Touch to win and advance


┌────────────────────────────────────────────────────────────────────────────┐
│ 📂 FOLDER STRUCTURE                                                       │
└────────────────────────────────────────────────────────────────────────────┘

AI-Powered-Adaptive-Gamified-Learning-Platform-for-Concept-Mastery/
├── Backend/                    ← Python API (FastAPI)
│   ├── api.py                 ← Main endpoint server
│   ├── database.py            ← SQLAlchemy models
│   ├── schemas.py             ← Data validation
│   └── requirements.txt        ← Python dependencies
│
├── AI-agents/                  ← Scene generation service
│   ├── main.py                ← FastAPI scene endpoint
│   ├── teacher_ai_agent.py    ← AI scene generator
│   ├── config.py              ← Configuration
│   ├── .env                   ← API keys (Groq, Gemini, etc.)
│   └── requirements.txt        ← Python dependencies
│
├── GameEngine/                 ← C++ game (OpenGL + physics)
│   ├── src/                   ← C++ source code
│   │   ├── main.cpp           ← Game entry point
│   │   ├── scene/             ← Scene loading
│   │   ├── systems/           ← Physics, rendering, etc.
│   │   └── educational/       ← Game mechanics
│   ├── data/
│   │   ├── scenes/            ← 📍 SCENE JSON FILES (for demo!)
│   │   │   ├── newtons_laws_grade7.json
│   │   │   ├── space___solar_system_grade8.json
│   │   │   ├── photosynthesis_grade5.json
│   │   │   └── ... more scenes
│   │   └── profiles/          ← User data storage
│   ├── assets/                ← Game assets
│   │   ├── images/            ← Theme folders with sprites
│   │   │   ├── space/
│   │   │   ├── photosynthesis/
│   │   │   └── physics/
│   │   ├── fonts/             ← Text rendering
│   │   └── audio/             ← Sound effects
│   ├── build/                 ← Compiled binary
│   │   └── Release/
│   │       └── EduEngine      ← 🎮 The game executable
│   ├── game_launcher.py       ← 🚀 Easy launcher script
│   └── README.md              ← Documentation
│
├── Frontend/                   ← React UI (not used in offline demo)
│   ├── src/
│   └── package.json
│
├── orchestrator.py            ← CLI workflow tool
├── verify_setup.py            ← Setup verification
└── README.md                   ← Platform overview


┌────────────────────────────────────────────────────────────────────────────┐
│ 🎬 LIVE DEMO FLOW (RECOMMENDED FOR JUDGES)                               │
└────────────────────────────────────────────────────────────────────────────┘

1️⃣ SETUP (Does not require)
   $ cd GameEngine/

2️⃣ LIST AVAILABLE GAMES
   $ python3 game_launcher.py list
   
   Output:
   📋 Available Scenes:
   
     • newtons_laws_grade7.json                   | Newton's 3 Laws of Motion — Grade 7
     • space___solar_system_grade8.json           | Space & Solar System — Grade 8
     • photosynthesis_grade5.json                 | Photosynthesis — Grade 5

3️⃣ START WITH A GAME
   $ python3 game_launcher.py newtons_laws_grade7.json
   
   Output:
   🚀 Launching EduEngine...
      Engine: ./build/Release/EduEngine
      Scene: newtons_laws_grade7.json
      ▶ Starting game (press ESC to exit)...

4️⃣ DEMONSTRATE GAMEPLAY
   • Move with arrow keys
   • Jump to reach platforms
   • Collect all 3 laws (LAW 1, LAW 2, LAW 3)
   • Touch "?" signs to see educational facts
   • Reach GOAL flag to complete level

5️⃣ GAME ENDS
   • Player wins by reaching goal with all collectibles
   • Game closes
   • Back to terminal prompt

6️⃣ OPTIONAL: Play another game
   $ python3 game_launcher.py space___solar_system_grade8.json


┌────────────────────────────────────────────────────────────────────────────┐
│ 🎯 WHAT JUDGES WILL SEE                                                   │
└────────────────────────────────────────────────────────────────────────────┘

DEMO HIGHLIGHTS:

✓ AI-Generated Scene JSON
  - Shows how AI creates complete game structure
  - Physics, colliders, platforms all configured
  - Grade-adaptive difficulty
  - Theme-specific content

✓ Working Game Engine
  - Smooth graphics and animations
  - Physics-based jumping and gravity
  - Collision detection working
  - Enemy AI patrolling

✓ Educational Content
  - Collectibles represent learning tokens
  - Info zones display actual facts
  - Grade 5: Simple, more platforms
  - Grade 8: Complex, more enemies, advanced content

✓ Real-Time Gameplay
  - AI-generated scene playable immediately
  - No loading delays
  - Fully offline
  - Zero dependencies


┌────────────────────────────────────────────────────────────────────────────┐
│ ❓ EXPECTED JUDGE QUESTIONS & ANSWERS                                    │
└────────────────────────────────────────────────────────────────────────────┘

Q: "Is this connected to AI right now?"
A: No! The scenes are pre-generated. The AI-Agent generates scenes when deployed,
   but for the demo, we're showing playable pre-made scenes stored locally.
   No API calls during gameplay.

Q: "How does the AI generate these scenes?"
A: The AI-Agents service takes a natural language prompt like "teach Newton's
   laws for grade 7" and generates a complete JSON scene file with all the
   physics, platforms, collectibles, and facts. It has fallback support:
   OpenAI → Gemini → Groq → Ollama

Q: "Can students customize scenes?"
A: Yes! Teachers can input a prompt and AI generates a custom scene. The JSON
   can also be manually edited.

Q: "What if internet goes down?"
A: No problem! All scenes are stored locally. The game runs 100% offline.
   AI scene generation requires internet, but gameplay doesn't.

Q: "How is this adaptive?"
A: Grade level changes difficulty:
   • Grade 5: Fewer platforms, no/slow enemies, more help
   • Grade 8: More platforms, faster enemies, harder challenges
   • Collectibles scale with grade complexity

Q: "How does physics work?"
A: C++ physics engine simulates gravity (980 units/s²), collision detection,
   jump mechanics, and one-way platforms. All from the JSON configuration.

Q: "Where's the educational content?"
A: In the JSON collectible labels and info zone facts. Stored locally, shown
   when player touches them.


┌────────────────────────────────────────────────────────────────────────────┐
│ ✅ TROUBLESHOOTING                                                         │
└────────────────────────────────────────────────────────────────────────────┘

Issue: "Command not found: game_launcher.py"
Fix: Make sure you're in the GameEngine directory
  $ cd GameEngine/
  $ python3 game_launcher.py

Issue: "Scene file not found"
Fix: Check scene exists using list command
  $ python3 game_launcher.py list

Issue: "No such file or directory: EduEngine"
Fix: Game engine not compiled yet. Compile it:
  $ cd GameEngine
  $ mkdir -p build && cd build
  $ cmake .. -DCMAKE_BUILD_TYPE=Release
  && make -j4

Issue: Game won't show graphics
Fix: Ensure OpenGL support. Try:
  $ LIBGL_ALWAYS_INDIRECT=1 ./build/Release/EduEngine data/scenes/newtons_laws_grade7.json

Issue: "Python not found"
Fix: Install Python 3.8+
  Ubuntu: sudo apt install python3
  macOS: brew install python3


┌────────────────────────────────────────────────────────────────────────────┐
│ 📊 SCORING & METRICS                                                      │
└────────────────────────────────────────────────────────────────────────────┘

The game tracks:
  ✓ Collectibles collected (per level)
  ✓ Time taken to complete
  ✓ Collision count (hitting enemies)
  ✓ Info zones viewed (educational engagement)
  ✓ Player score (all of the above combined)

Full system also tracks (when Backend is running):
  ✓ User progress across sessions
  ✓ Learning path completion
  ✓ Concept mastery level
  ✓ Performance metrics per subject


┌────────────────────────────────────────────────────────────────────────────┐
│ 🚀 DEPLOYMENT NOTES                                                        │
└────────────────────────────────────────────────────────────────────────────┘

For Students/Teachers:
  1. Pre-generate scenes for offline play
  2. Include GameEngine directory
  3. No API keys needed
  4. Just run: python3 game_launcher.py

For Production:
  1. Backend API handles user auth and storage
  2. Frontend React app for scene selection
  3. GameEngine embedded or called as subprocess
  4. AI-Agents service generates scenes on demand
  5. All scenes cached locally


┌────────────────────────────────────────────────────────────────────────────┐
│ 📞 FINAL NOTES FOR JUDGES                                                 │
└────────────────────────────────────────────────────────────────────────────┘

This demo showcases:
  ✅ AI-generated game content (scenes as JSON)
  ✅ Full game engine implementation (C++ with physics)
  ✅ Educational interactivity (collectibles + facts)
  ✅ Grade-adaptive difficulty
  ✅ Complete platform architecture (Backend + AI + Frontend)
  ✅ Offline-first design (no internet required to play)
  ✅ Zero API key exposure in demo

The platform is production-ready and can be deployed as:
  • Web application (React frontend)
  • Mobile app (game engine cross-compiled)
  • Desktop application
  • Classroom learning management system

Thank you for reviewing our project!
"""

def main():
    """Print the demo guide"""
    center_text = lambda x: x.center(80)
    
    print(DEMO_GUIDE)
    
    # Save to file
    script_dir = Path(__file__).parent
    output_file = script_dir / "DEMO_GUIDE.txt"
    
    with open(output_file, 'w') as f:
        f.write(DEMO_GUIDE)
    
    print(f"\n📄 Guide saved to: {output_file}")
    print("\n" + "="*80)
    print("Ready to demo! Run: python3 game_launcher.py")
    print("="*80 + "\n")

if __name__ == "__main__":
    main()
